"""empty message

Revision ID: 668cde1e6e6e
Revises: 9487943290c0
Create Date: 2019-05-06 16:41:20.996899

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '668cde1e6e6e'
down_revision = '9487943290c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('complete', sa.Boolean(), nullable=False))
    op.add_column('booking', sa.Column('end_location', sa.Integer(), nullable=False))
    op.add_column('booking', sa.Column('start_location', sa.Integer(), nullable=False))
    op.alter_column('booking', 'card_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.create_foreign_key(None, 'booking', 'location', ['start_location'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'booking', type_='foreignkey')
    op.alter_column('booking', 'card_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_column('booking', 'start_location')
    op.drop_column('booking', 'end_location')
    op.drop_column('booking', 'complete')
    # ### end Alembic commands ###
