"""empty message

Revision ID: 9487943290c0
Revises: 
Create Date: 2019-02-23 20:06:40.403383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9487943290c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('bike_amount', sa.Integer(), nullable=False),
    sa.Column('max_capacity', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=80), nullable=False),
    sa.Column('addr', sa.Text(), nullable=False),
    sa.Column('longt', sa.Float(), nullable=True),
    sa.Column('latt', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('image', sa.String(length=75), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('user_type', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('bike',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('in_use', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_number', sa.String(length=15), nullable=False),
    sa.Column('card_name', sa.String(length=40), nullable=False),
    sa.Column('security_no', sa.Integer(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('card_type', sa.String(length=20), nullable=False),
    sa.Column('addr_first', sa.String(length=20), nullable=False),
    sa.Column('addr_second', sa.String(length=20), nullable=True),
    sa.Column('addr_towncity', sa.String(length=20), nullable=False),
    sa.Column('addr_county', sa.String(length=20), nullable=True),
    sa.Column('addr_postcode', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_number')
    )
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('bike_amount', sa.Integer(), nullable=False),
    sa.Column('late_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('booking_time', sa.DateTime(), nullable=False),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booked_bike',
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('bike_id', sa.Integer(), nullable=False),
    sa.Column('taken', sa.Boolean(), nullable=False),
    sa.Column('returned', sa.Boolean(), nullable=False),
    sa.Column('return_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bike_id'], ['bike.id'], ),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ),
    sa.PrimaryKeyConstraint('booking_id', 'bike_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booked_bike')
    op.drop_table('booking')
    op.drop_table('card')
    op.drop_table('bike')
    op.drop_table('user')
    op.drop_table('location')
    # ### end Alembic commands ###
